version: '3'

services:
  app:
    # build:
    #   context: ./nginx_com_node/
    #   dockerfile: Dockerfile-node
    image: domrafael/nginx_com_node-app
    container_name: app
    entrypoint: | 
      dockerize --wait tcp://db:3306 
      --timeout 20s 
      docker-entrypoint.sh 
      npm start 
    networks:
      - net-app
    tty: true
    depends_on:
      - db

  nginx:
    # build:
    #   context: ./nginx_com_node/
    #   dockerfile: Dockerfile-nginx
    image: domrafael/nginx_com_node-nginx
    container_name: nginx
    entrypoint: | 
      dockerize --wait http://app:3000
      --timeout 20s 
      /docker-entrypoint.sh 
      nginx -g 'daemon off;' 
    networks:
      - net-app
    tty: true
    ports:
      - '8080:80'
      - '8443:443'
    depends_on:
      - app

  db:
    image: mysql:8
    command: | 
      --default-authentication-plugin=mysql_native_password 
      --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=S3cr3t0
      - MYSQL_PASSWORD=S3cr3t0
      - MYSQL_USER=people
    networks:
      - net-app

networks:
  net-app:
    driver: bridge

volumes:
  db-data:
